[providers.docker]
exposedByDefault = false

[providers.file]
directory = "/traefik-dynamic"
watch = true

[api]
# debug = true # 默认 false
insecure = true # 默认 false

[entryPoints.web]
address = ":80"
[entryPoints.web.http.redirections.entryPoint]
scheme = "https"
to = "websecure"

[entryPoints.websecure]
address = ":443"
