site_name: 基于Web的通用系统后端和管理界面
site_author: Grant Zhang
site_dir: dist
copyright: MIT Licensed | Copyright © 2021 Grant Zhang
theme:
  name: material
  language: zh
  palette:
    primary: blue grey
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
plugins:
  - search:
      lang: zh
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gntzh
nav:
  - 快速开始:
      - guides/index.md
      - guides/deployment.md
  - about.md
