site_name: 基于Web的通用系统后端和管理界面
site_author: Grant Zhang
site_dir: dist
repo_url: https://github.com/gntzh/ed-proj/
edit_uri: edit/main/docs/docs/
copyright: MIT Licensed | Copyright © 2021 Grant Zhang
theme:
  name: material
  language: zh
  palette:
    primary: blue grey
  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
plugins:
  - search:
      lang: zh
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gntzh
nav:
  - 开始:
      - guides/quick-start.md
      - guides/deployment.md
  - about.md
markdown_extensions:
  - attr_list
